image: node:8.8.1

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

before_script:
  - npm install

test:
  stage: test
  script:
    - npm test

publish:
  stage: deploy
  only:
    - tags
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
